config/routes.rb
Rails.application.routes.draw do
  root to: 'qrcodes#new'

  resources :qrcodes, only: %i[new create show]
end

app/models/address.rb
class Address < ApplicationRecord
  validates :token, :crypto_name, presence: true

  belongs_to :wallet

  def as_json
    {
      token: token,
      crypto_name: crypto_name
    }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  before_validation :generate_token

  validates :token, presence: true, uniqueness: true

  has_many :addresses, dependent: :destroy

  protected

  def generate_token
    self.token = SecureRandom.urlsafe_base64
    generate_token if Wallet.exists?(token: token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/qrcodes_controller.rb
require 'net/http'
require 'json'

class QrcodesController < ApplicationController
  def new
    @crypto_names = %w[ETH BTC].sort
  end

  def create
    new_wallet = Wallet.new
    wallets_params[:wallets].map do |wallet|
      new_wallet.addresses << Address.new(wallet)
    end

    new_wallet.save! || render(status: 422)
    render json: { 'token': new_wallet.token }, status: 200
  end

  def show
    addresses = Wallet.find_by(token: params[:id]).addresses.map(&:as_json)
    render json: { 'wallets': addresses }, status: 200
  end

  private

  def wallets_params
    params.require(:qrcode).permit(wallets: %i[crypto_name token])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qrcode_helper.rb
module QrcodeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/qrcode/create.html.erb
<%= tag :div, data: { cryptoNames: @crypto_names } %>

<div class="grid-container">
  <div id="qrcode" class="qrcode">
    <div class="qrcode--stetup-message">
      Enter your wallets and then generate the qrcode.
    </div>
  </div>

  <div class="qrcode--generate">
    <button onClick="generateQrCode()" class="qrcode--generate--button" type="button">
      Generate QR Code
    </button>
  </div>

  <div class="qrcode--wallet--list"></div>

  <div class="qrcode--wallet--list--add-wallet">
    <button onClick="renderNewWallet()" class="qrcode--wallet--list--add-wallet--button" type="button">
      +
    </button>
  </div>
</div>

app/views/qrcode/new.html.erb
<%= link_to raw("<i class='fa fa-arrow-left'></i>"), qrcode_index_path, class: 'qrcode--back--button', method: :get, disabled: true %>

<div class="grid-container--new">
  <div id="qrcode" class="qrcode">
    <div class="qrcode--stetup-message">
      Enter your wallets and then generate the qrcode.
    </div>
  </div>

  <div class="qrcode--generate">
    <button onClick="generateQrCode()" class="qrcode--generate--button" type="button">
      Generate QR Code
    </button>
  </div>

  <div class="qrcode--wallet--list"></div>

  <div class="qrcode--wallet--list--add-wallet">
    <button onClick="renderNewWallet()" class="qrcode--wallet--list--add-wallet--button" type="button">
      +
    </button>
  </div>
</div>
<%= tag :div, data: { cryptoNames: @crypto_names } %>

app/views/qrcodes/new.html.erb
<div class="grid-container">
  <div id="qrcode" class="qrcode">
    <div class="qrcode--message">
      Enter your wallets and then generate the qrcode.
    </div>
  </div>

  <div class="qrcode--generate">
    <button onClick="saveWallets()" class="qrcode--generate--button" type="button">
      Generate QR Code
    </button>
  </div>

  <div class="qrcode--load">
    <input  class="qrcode--load--token" type="text" placeholder="your token"/>
    <button onClick="loadWallets()" class="qrcode--load--button" type="button">
      <i class="fa fa-download"></i>
    </button>
  </div>

  <div class="qrcode--wallet--list"></div>

  <div class="qrcode--wallet--list--add-wallet">
    <button onClick="renderNewWallet()" class="qrcode--wallet--list--add-wallet--button" type="button">
      +
    </button>
  </div>
</div>

<%= tag :div, data: { cryptoNames: @crypto_names } %>